unlink("grid", recursive = TRUE)
message("Modifying the tools package.")
source("~/notes/grid-notes/install-base.R")
tools:::.build_packages(".")
untar("grid_1.1.tar.gz")
tools:::.install_packages("grid")
unlink("grid_1.1.tar.gz")
message("Please restart R to restore tools.")